TenderDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from user.views import signup
from login.views import hpage

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('login/',auth_views.LoginView.as_view(template_name='login/login.html'),name='login'),
     path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='login/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='login/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='login/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='login/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('hpage/',hpage,name="page_home"),
    path('contractor/', include('contractor.urls')),
    path('user/', include('user.urls')),
    path('signup/',signup,name="signup"),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import UserTenderlistview,regusertender,mybiddings,userhome,confirmedbiddings,uprofile
from django.contrib.auth import views as auth_views

app_name='user'
urlpatterns = [
    path('',userhome),
    path('uprofile/',uprofile,name="uprofile"),
    path('tenderlist/',UserTenderlistview.as_view(),name="user-tender-list"),
    path('registerusertender/<str:tendername>/<str:contractorname>/<int:baseprice>/',regusertender),
    path('mybiddings/',mybiddings,name='userbiddings'),
    path('confirmedbiddings',confirmedbiddings,name="confirmed_biddings"),
    path('logout/',auth_views.LogoutView.as_view(template_name='contractor/logout.html'),name='ulogout'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class UserTender(models.Model):
    Tendername=models.CharField(max_length=120)
    Contractorname=models.CharField(max_length=120)
    Name=models.CharField(max_length=120)
    User=models.ForeignKey(User,on_delete=models.CASCADE)
    Bidprice=models.IntegerField()

    def get_absolute_url(self):
        return reverse('user:userbiddings',args=[self.Name,])
    

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserTender
from contractor.models import Profile

class RawUserForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class UserTenderForm(forms.ModelForm):
    class Meta:
        model=UserTender
        fields=[
            'Tendername',
            'Contractorname',
            'Name',
            'User',
            'Bidprice'
            ]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

user/views.py
from django.http import HttpRequest
from django.shortcuts import render,redirect
from .forms import RawUserForm
from contractor.models import Tender,ConfirmTender
from django.views.generic import ListView
from .forms import UserTenderForm,UserUpdateForm,ProfileUpdateForm
from .models import UserTender
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages

# Create your views here.
class UserTenderlistview(ListView):
    model=Tender
    template_name="user/user_tender.html"
    context_object_name='tenders'

def signup(request):
    if request.method=="POST":
        form=RawUserForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Account created for {username}!')
            return redirect('/login/')
    else:
        form=RawUserForm()
    return render(request,'user/registeruser.html',{'form':form})

def regusertender(request,tendername,contractorname,baseprice):
    print(baseprice)
    if request.method=="POST":
        form=UserTenderForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            bidprice=request.POST.get('Bidprice')
            if int(bidprice) <= baseprice:
                return render(request,'login/invalid.html')
            UserTender.objects.create(**form.cleaned_data)
            return redirect('/contractor/regsuccess/')
    else:
        form=UserTenderForm(initial={'Tendername': tendername, 'Contractorname': contractorname, 'Bidprice': baseprice})
        
    context={'form':form}
    return render(request,"user/user_tender_reg.html",context)

def mybiddings(request):
    current_user=request.user
    uname=current_user.username
    print(uname)
    query=UserTender.objects.all().filter(Name=uname)
    # print(query.first())
    # for i in query:
    #     print(i.Name)
    # print(current_user)
    context={
        'data':query
    }
    return render(request,'user/userbiddings.html',context)

def userhome(request):
    return render(request,"user/userhome.html")

def confirmedbiddings(request):
    uname=request.user.username
    query=ConfirmTender.objects.all().filter(Username=uname)
    context={
        'data':query
    }
    return render(request,'user/userbiddings.html',context)

@login_required
def uprofile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('user:uprofile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'user/uprofile.html', context)

user/templates/user/registeruser.html
{% extends "login/main.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Signup</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="/login/">Sign In</a>
                </small>
            </div>
        </form>
        
    </div>
    <style>
        form {
    width: 500px;
    background: #fff;
    padding: 15px 40px 40px;
    border: 1px solid #ccc;
    margin: 50px auto 0;
    border-radius: 5px;
}
    </style>
{% endblock content %}

user/templates/user/uprofile.html
{% extends "user/userhome.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="tender-box1">
<div class="content-section">
    <div class="media">
        <img class=" test rounded-circle" src="{{user.profile.image.url}}">
        <div class="media-body">
            <br/>
            <h2 class="account-heading">&nbsp;&nbsp;{{user.username}}</h2>
            <p class="text-secondary">&nbsp;&nbsp;{{user.email}}</p>
        </div>
    </div>
    <br/>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
</div>
</div>
{% endblock content %}

user/templates/user/user_tender.html
{% extends "user/userhome.html" %}
{% block content %}
{% for instance in tenders %}
<div class="tender-box">
<h4><b>{{instance.Tendername}}</b></h4>
<h5>Base Price : {{instance.Baseprice}}</h5>
<h5>Deadline : {{instance.Deadline}}</h5>
<a href="../../user/registerusertender/{{instance.Tendername}}/{{instance.ContractorName}}/{{instance.Baseprice}}">Register</a>
</div>
{% endfor %}
{% endblock %}

user/templates/user/user_tender_reg.html
{% extends 'user/userhome.html' %}
{% block content1 %}
<br/>
<h3 style="color: rgba(255, 255, 255, 0.856); text-align: center; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;">Bid Tender</h3>
{% endblock %}
{% block content %}
        <form class="form1" action="." method='POST'>{% csrf_token %}
            {{form.as_p}}
        <input type="submit" class="sb" value="Submit">&nbsp;&nbsp;
        <input type="reset" value="Reset">
        </form>
{% endblock %}

user/templates/user/userbiddings.html
{% extends "user/userhome.html" %}
{% block content %}
{% for instance in data %}
<div class="tender-box">
<h4><b>{{instance.Tendername}}</b></h4>
<h5>Deadline : {{instance.Contractorname}}</h5>
<h5>Bid Price : {{instance.Bidprice}}</h5>
</div>
{% endfor %}
{% endblock %}

user/templates/user/userhome.html
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>

<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet" />
	
</head>
<body >
	<div class="container-fluid banner">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-md">
					<div class="navbar-brand">User Portal</div>
					<ul class="nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'user:uprofile'%}">Profile <span class="sr-only">(current)</span></a>
                        </li>
						<li class="nav-item active">
                            <!-- url 'user-tender-list' -->
                            <a class="nav-link" href="{% url 'user:user-tender-list'%}">Register Tender <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <!-- /user/mybiddings/{{Username}}/ -->
                            <a class="nav-link" href="{% url 'user:userbiddings' %}">My Biddings <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'user:confirmed_biddings' %}">Confirm Biddings <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'user:ulogout'%}">Logout <span class="sr-only">(current)</span></a>
                        </li>
					</ul>
				</nav>
			</div>
            <!-- <h1>{{request.user}}</h1> -->
		</div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{ message }}
        </div>
        {% block content1 %}
        {% endblock %}
        {% block content%}
        <br/><br/><br/><br/><br/><br/><br/><br/>
        <h2 style="color: white;"><center>Welcome {{request.user}}</center></h2>
        {% endblock %}
	</div>
    
</body>
<style>
	body{
	margin:0;
	padding:0;
	/* background:#fff; */
	font-family: 'Raleway',sans-serif;
	background-color: rgb(38, 140, 165);
	/* color: #fff; */
}
.banner{
	height: 100vh;
	width: 100%;
	/*
	background:url('/static/css/banner.jpg'),url("/static/css/banner.jpg");
	background-position: top;
	background-size:cover;
	background-attachment: fixed;
	background-repeat: no-repeat; */
	background-color: rgb(38, 140, 165);
}
.banner .navbar{
	margin-top:4px;
}
.banner .navbar-brand{
	color: #fff;
	font-size:1.8em;
	font-weight: 700;
	margin-left: 10%;
}
.banner .nav{
	margin-right:10%; 
}
.banner .nav li a{
	color:rgb(238, 230, 230);
	font-size: 1.2em;
}
.banner .info{
	margin-top:15%;
	transform: translateY(-15%);
}
.banner .info h1{
	font-size: 2.5em;
	font-weight: 700;
	color: #fff;
	letter-spacing: 2px;
}
.banner .info p{
	font-size: 2em;
	font-weight: 500;
	color: #aaa;
	letter-spacing: 2px;
}
.banner .info a{
	margin-left:50%;
	transform: translateX(-50%);
	color: #fff;
	background: #e91d43;
	padding:10px 20px; 
	font-size: 1em;
	font-weight: 600;
}
.banner .info a:hover{
	background: #e91e63;
}

.form1 {
    width: 330px;
    height: 470px;
    background: #fff;
    padding: 15px 40px 40px;
    border: 1px solid #ccc;
    margin: 20px auto 0;
    border-radius: 5px;
}

.test {
  width: 120px;
  height: 120px;
}

.tender-box{
    width: 900px;
    height: 180px;
    background: rgba(255, 255, 255, 0.87);
    padding: 15px 40px 40px;
    border: 1px solid rgb(2, 69, 114);
    margin: 20px auto 0;
    border-radius: 5px;
}

.tender-box1{
    width: 900px;
    height: 640px;
    background: rgba(255, 255, 255, 0.87);
    padding: 15px 40px 40px;
    border: 1px solid rgb(2, 69, 114);
    margin: 20px auto 0;
    border-radius: 5px;
}

label {
    display: block;
    margin-bottom: 5px
}
label i {
    color: #999;
    font-size: 80%;
}
input, select {
    border: 1px solid #ccc;
    padding: 10px;
    display: block;
    width: 100%;
    box-sizing: border-box;
    border-radius: 2px;
}
.row {
    padding-bottom: 10px;
}
.form-inline {
    border: 1px solid #ccc;
    padding: 8px 10px 4px;
    border-radius: 2px;
}
.form-inline label, .form-inline input {
    display: inline-block;
    width: auto;
    padding-right: 15px;
}
.error {
    color: red;
    font-size: 90%;
}
.rb {
    width:15%;
    height: 30%;
    font-size: 100%;
    font-weight: 80;
    background: #006dcc;
    border-color: #016BC1;
    box-shadow: 0 3px 0 #0165b6;
    color: #fff;
    margin-top: 10px;
    cursor: pointer;
}
.rb:hover {
    background: #0165b6;
}

.sb{
    width:45%;
    font-size: 110%;
    font-weight: 100;
    background: #006dcc;
    border-color: #016BC1;
    box-shadow: 0 3px 0 #0165b6;
    color: #fff;
    margin-top: 10px;
    cursor: pointer;
}

.sb:hover {
    background: #0165b6;
}

input[type="reset"] {
    width:45%;
    font-size: 110%;
    font-weight: 100;
    background: #006dcc;
    border-color: #016BC1;
    box-shadow: 0 3px 0 #0165b6;
    color: #fff;
    margin-top: 10px;
    cursor: pointer;
}
input[type="reset"]:hover {
    background: #0165b6;
}
input[type="submit"],input[type="reset"]{
    display: inline-block;
}
</style>
</html>